---
spring:
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: "true"
    hibernate:
      ddl-auto: "create-drop"
    show-sql: "true"
  application:
    name: "urfuhelper"
  datasource:
    password: ${DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: "TRACE"
        SQL: "DEBUG"
server:
  port: ${APPLICATION_PORT}