---
spring:
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: "true"
    hibernate:
      ddl-auto: "create-drop"
    show-sql: "true"
  application:
    name: "urfuhelper"
  datasource:
    password: ${DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: "TRACE"
        SQL: "DEBUG"
  urfu:
    student:
      helper:
        security: "DEBUG"
server:
  port: ${APPLICATION_PORT}
app:
  jwt:
    secret: ${JWT_SECRET}

  session:
    timeout-minutes: "120"
  cors:
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allowed-origins: "*"
    allow-credentials: "true"